version: '3.8'

services:
  db_citas:
    image: postgres:15-alpine
    container_name: postgres_citas_db
    restart: always
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: citas_online_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_citas_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-postgres}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - db_citas

  backend:
    build:
      context: ./backend
    container_name: flask_backend
    command: sh -c "flask db upgrade && flask run --host=0.0.0.0 --port=5000"
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "5001:5000"
    env_file:
      - ./backend/.env 
    environment:
      FLASK_APP: run.py
      # Solo sobrescribimos las variables que DEBEN ser diferentes en Docker
      DB_HOST: db_citas
      # Eliminamos las duplicadas que ya están en .env para evitar conflictos
    depends_on:
      - db_citas

  frontend:
    build:
      context: ./frontend
    container_name: vite_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  mailhog:
      image: mailhog/mailhog
      container_name: 'mailhog'
      ports:
        - "1025:1025"
        - "8025:8025"

volumes:
  postgres_citas_data: