"""add webhook_events table

Revision ID: 14840a4e8003
Revises: 9d1f7048c9a9
Create Date: 2025-08-19 15:00:55.345838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14840a4e8003'
down_revision = '9d1f7048c9a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=100), nullable=True),
    sa.Column('from_msisdn', sa.String(length=32), nullable=True),
    sa.Column('keyword_detected', sa.String(length=32), nullable=True),
    sa.Column('invite_token', sa.String(length=64), nullable=True),
    sa.Column('sent_ok', sa.Boolean(), nullable=False),
    sa.Column('error_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_events_from_msisdn'), ['from_msisdn'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_events_invite_token'), ['invite_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_events_message_id'), ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_events_message_id'))
        batch_op.drop_index(batch_op.f('ix_webhook_events_invite_token'))
        batch_op.drop_index(batch_op.f('ix_webhook_events_from_msisdn'))
        batch_op.drop_index(batch_op.f('ix_webhook_events_created_at'))

    op.drop_table('webhook_events')
    # ### end Alembic commands ###
