"""Simplify Provider model by removing redundant user_id column

Revision ID: 177cd566f81d
Revises: 8e0ced908053
Create Date: 2025-07-01 16:21:18.940641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177cd566f81d'
down_revision = '8e0ced908053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('establecimiento_tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_index('ix_providers_user_id')
        batch_op.drop_constraint('providers_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('time_blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_blocks', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('providers_user_id_fkey', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_index('ix_providers_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('establecimiento_tags', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
