"""add phone_otps table

Revision ID: 240227f59ced
Revises: dd0430c6d0fa
Create Date: 2025-08-14 12:13:30.413288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240227f59ced'
down_revision = 'dd0430c6d0fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('phone_e164', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phone_otps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phone_otps_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_phone_otps_phone_e164'), ['phone_e164'], unique=False)
        batch_op.create_index(batch_op.f('ix_phone_otps_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_phone_otps_used_at'), ['used_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_phone_otps_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('magic_links', schema=None) as batch_op:
        batch_op.drop_index('ix_magic_links_expires')
        batch_op.drop_index('ix_magic_links_used')
        batch_op.drop_index('ix_magic_links_user')
        batch_op.create_index(batch_op.f('ix_magic_links_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_magic_links_used_at'), ['used_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('magic_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_magic_links_used_at'))
        batch_op.drop_index(batch_op.f('ix_magic_links_expires_at'))
        batch_op.create_index('ix_magic_links_user', ['user_id'], unique=False)
        batch_op.create_index('ix_magic_links_used', ['used_at'], unique=False)
        batch_op.create_index('ix_magic_links_expires', ['expires_at'], unique=False)

    with op.batch_alter_table('phone_otps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phone_otps_user_id'))
        batch_op.drop_index(batch_op.f('ix_phone_otps_used_at'))
        batch_op.drop_index(batch_op.f('ix_phone_otps_purpose'))
        batch_op.drop_index(batch_op.f('ix_phone_otps_phone_e164'))
        batch_op.drop_index(batch_op.f('ix_phone_otps_expires_at'))

    op.drop_table('phone_otps')
    # ### end Alembic commands ###
