"""add attempts to phone_otps

Revision ID: 35ab7f11c179
Revises: 82e465b06087
Create Date: 2025-08-14 15:09:58.236343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ab7f11c179'
down_revision = '82e465b06087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_otps', schema=None) as batch_op:
        batch_op.drop_index('ix_phone_otps_user_id')
        batch_op.create_index(batch_op.f('ix_phone_otps_attempts'), ['attempts'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_otps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phone_otps_attempts'))
        batch_op.create_index('ix_phone_otps_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###
