"""add attempts to phone_otps

Revision ID: 82e465b06087
Revises: 240227f59ced
Create Date: 2025-08-14 14:03:31.590815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e465b06087'
down_revision = '240227f59ced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_otps', schema=None) as batch_op:
        batch_op.alter_column('phone_e164',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_otps', schema=None) as batch_op:
        batch_op.alter_column('phone_e164',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###
