"""add new models

Revision ID: 8e0ced908053
Revises: 2db4cf95bb75
Create Date: 2025-06-10 11:30:13.260402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e0ced908053'
down_revision = '2db4cf95bb75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('icono', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', 'tipo', name='uix_nombre_tipo')
    )
    op.create_table('establishments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('direccion_completa', sa.String(length=255), nullable=False),
    sa.Column('codigo_postal', sa.String(length=10), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=False),
    sa.Column('localidad', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('web', sa.String(length=255), nullable=True),
    sa.Column('abre_sabados', sa.Boolean(), nullable=True),
    sa.Column('cierra_sabado', sa.Boolean(), nullable=True),
    sa.Column('visible_en_busquedas', sa.Boolean(), nullable=True),
    sa.Column('verificado', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('descripcion_publica', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('imagen_destacada', sa.String(length=255), nullable=True),
    sa.Column('url_map_embed', sa.String(length=255), nullable=True),
    sa.Column('tiene_acceso_discapacitados', sa.Boolean(), nullable=True),
    sa.Column('aparcamiento_disponible', sa.Boolean(), nullable=True),
    sa.Column('idiomas_hablados', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('horario_lunes_viernes', sa.String(length=100), nullable=True),
    sa.Column('horario_sabado', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.provider_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('establishments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_establishments_localidad'), ['localidad'], unique=False)
        batch_op.create_index(batch_op.f('ix_establishments_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_establishments_provincia'), ['provincia'], unique=False)
        batch_op.create_index(batch_op.f('ix_establishments_slug'), ['slug'], unique=True)

    op.create_table('establecimiento_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('establecimiento_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['establishments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('establecimiento_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_establecimiento_tags_establecimiento_id'), ['establecimiento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_establecimiento_tags_tag_id'), ['tag_id'], unique=False)

    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('establishment_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=100), nullable=False),
    sa.Column('email_contacto', sa.String(length=100), nullable=True),
    sa.Column('telefono_contacto', sa.String(length=50), nullable=True),
    sa.Column('imagen_perfil', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('visible_web', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_establishment_id'), ['establishment_id'], unique=False)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('estado', postgresql.ENUM('PENDING_PROVIDER', 'CONFIRMED', 'CANCELLED_BY_CLIENT', 'CANCELLED_BY_PROVIDER', 'COMPLETED', 'NO_SHOW', name='appointmentstatustype_enum'), nullable=False))
        batch_op.add_column(sa.Column('notas_cliente', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notas_internas', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('requiere_confirmacion', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('origen_reserva', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('precio_final', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.alter_column('service_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index('ix_appointments_client_id')
        batch_op.drop_index('ix_appointments_provider_id')
        batch_op.drop_index('ix_appointments_start_datetime')
        batch_op.drop_index('ix_appointments_status')
        batch_op.create_index(batch_op.f('ix_appointments_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint('appointments_client_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('appointments_provider_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='SET NULL')
        batch_op.drop_column('notes_provider')
        batch_op.drop_column('end_datetime')
        batch_op.drop_column('notes_client')
        batch_op.drop_column('start_datetime')
        batch_op.drop_column('client_id')
        batch_op.drop_column('provider_id')
        batch_op.drop_column('status')

    with op.batch_alter_table('availability_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('establishment_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('dia_semana', postgresql.ENUM('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO', name='dayofweektype_enum'), nullable=False))
        batch_op.add_column(sa.Column('hora_inicio', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('hora_fin', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=False))
        batch_op.drop_index('ix_availability_rules_provider_id')
        batch_op.create_index(batch_op.f('ix_availability_rules_activo'), ['activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_availability_rules_dia_semana'), ['dia_semana'], unique=False)
        batch_op.create_index(batch_op.f('ix_availability_rules_establishment_id'), ['establishment_id'], unique=False)
        batch_op.drop_constraint('availability_rules_provider_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'establishments', ['establishment_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('provider_id')
        batch_op.drop_column('start_time')
        batch_op.drop_column('day_of_week')
        batch_op.drop_column('end_time')

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('nombre_comercial', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('cif', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('tipo_empresa', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('imagen_perfil_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('telefono_contacto', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('email_contacto', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('web', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('verificado', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('idiomas_hablados', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('direccion_fiscal', sa.String(length=255), nullable=True))
        batch_op.alter_column('timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_providers_cif'), ['cif'], unique=True)
        batch_op.create_index(batch_op.f('ix_providers_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_providers_verificado'), ['verificado'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.drop_column('address')
        batch_op.drop_column('business_type')
        batch_op.drop_column('business_name')
        batch_op.drop_column('profile_picture_url')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('establishment_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('nombre', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('duracion_minutos', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('categoria', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('orden', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('requiere_confirmacion_manual', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('limite_reservas_diarias', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_services_provider_id')
        batch_op.create_index(batch_op.f('ix_services_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_establishment_id'), ['establishment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_is_active'), ['is_active'], unique=False)
        batch_op.create_unique_constraint('uix_establishment_nombre', ['establishment_id', 'nombre'])
        batch_op.drop_constraint('services_provider_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'establishments', ['establishment_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('duration_minutes')
        batch_op.drop_column('description')
        batch_op.drop_column('name')
        batch_op.drop_column('price')
        batch_op.drop_column('provider_id')

    with op.batch_alter_table('time_blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('establishment_id', sa.Integer(), nullable=False))
        batch_op.drop_index('ix_time_blocks_provider_id')
        batch_op.create_index(batch_op.f('ix_time_blocks_establishment_id'), ['establishment_id'], unique=False)
        batch_op.drop_constraint('time_blocks_provider_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'establishments', ['establishment_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('provider_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('time_blocks_provider_id_fkey', 'providers', ['provider_id'], ['provider_id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_time_blocks_establishment_id'))
        batch_op.create_index('ix_time_blocks_provider_id', ['provider_id'], unique=False)
        batch_op.drop_column('establishment_id')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('services_provider_id_fkey', 'providers', ['provider_id'], ['provider_id'], ondelete='CASCADE')
        batch_op.drop_constraint('uix_establishment_nombre', type_='unique')
        batch_op.drop_index(batch_op.f('ix_services_is_active'))
        batch_op.drop_index(batch_op.f('ix_services_establishment_id'))
        batch_op.drop_index(batch_op.f('ix_services_categoria'))
        batch_op.create_index('ix_services_provider_id', ['provider_id'], unique=False)
        batch_op.drop_column('limite_reservas_diarias')
        batch_op.drop_column('requiere_confirmacion_manual')
        batch_op.drop_column('orden')
        batch_op.drop_column('categoria')
        batch_op.drop_column('precio')
        batch_op.drop_column('duracion_minutos')
        batch_op.drop_column('descripcion')
        batch_op.drop_column('nombre')
        batch_op.drop_column('establishment_id')

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('business_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('business_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_providers_verificado'))
        batch_op.drop_index(batch_op.f('ix_providers_user_id'))
        batch_op.drop_index(batch_op.f('ix_providers_cif'))
        batch_op.alter_column('timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('direccion_fiscal')
        batch_op.drop_column('idiomas_hablados')
        batch_op.drop_column('activo')
        batch_op.drop_column('verificado')
        batch_op.drop_column('web')
        batch_op.drop_column('email_contacto')
        batch_op.drop_column('telefono_contacto')
        batch_op.drop_column('imagen_perfil_url')
        batch_op.drop_column('tipo_empresa')
        batch_op.drop_column('cif')
        batch_op.drop_column('nombre_comercial')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('availability_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('day_of_week', postgresql.ENUM('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO', name='dayofweektype_enum'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('availability_rules_provider_id_fkey', 'providers', ['provider_id'], ['provider_id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_availability_rules_establishment_id'))
        batch_op.drop_index(batch_op.f('ix_availability_rules_dia_semana'))
        batch_op.drop_index(batch_op.f('ix_availability_rules_activo'))
        batch_op.create_index('ix_availability_rules_provider_id', ['provider_id'], unique=False)
        batch_op.drop_column('activo')
        batch_op.drop_column('hora_fin')
        batch_op.drop_column('hora_inicio')
        batch_op.drop_column('dia_semana')
        batch_op.drop_column('establishment_id')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', postgresql.ENUM('PENDING_PROVIDER', 'CONFIRMED', 'CANCELLED_BY_CLIENT', 'CANCELLED_BY_PROVIDER', 'COMPLETED', 'NO_SHOW', name='appointmentstatustype_enum'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('start_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('notes_client', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('end_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('notes_provider', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('appointments_provider_id_fkey', 'providers', ['provider_id'], ['provider_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('appointments_client_id_fkey', 'users', ['client_id'], ['user_id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_appointments_user_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_start_time'))
        batch_op.drop_index(batch_op.f('ix_appointments_estado'))
        batch_op.create_index('ix_appointments_status', ['status'], unique=False)
        batch_op.create_index('ix_appointments_start_datetime', ['start_datetime'], unique=False)
        batch_op.create_index('ix_appointments_provider_id', ['provider_id'], unique=False)
        batch_op.create_index('ix_appointments_client_id', ['client_id'], unique=False)
        batch_op.alter_column('service_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('precio_final')
        batch_op.drop_column('origen_reserva')
        batch_op.drop_column('requiere_confirmacion')
        batch_op.drop_column('notas_internas')
        batch_op.drop_column('notas_cliente')
        batch_op.drop_column('estado')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_establishment_id'))

    op.drop_table('staff')
    with op.batch_alter_table('establecimiento_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_establecimiento_tags_tag_id'))
        batch_op.drop_index(batch_op.f('ix_establecimiento_tags_establecimiento_id'))

    op.drop_table('establecimiento_tags')
    with op.batch_alter_table('establishments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_establishments_slug'))
        batch_op.drop_index(batch_op.f('ix_establishments_provincia'))
        batch_op.drop_index(batch_op.f('ix_establishments_provider_id'))
        batch_op.drop_index(batch_op.f('ix_establishments_localidad'))

    op.drop_table('establishments')
    op.drop_table('tags')
    # ### end Alembic commands ###
