"""add next_path to whatsapp_invites

Revision ID: 9d1f7048c9a9
Revises: dfd4eed74b06
Create Date: 2025-08-15 16:16:22.681864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d1f7048c9a9'
down_revision = 'dfd4eed74b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_invites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_invites', schema=None) as batch_op:
        batch_op.drop_column('next_path')

    # ### end Alembic commands ###
