"""Add staff availability rules

Revision ID: b8dec5209111
Revises: ed182a6fc9c8
Create Date: 2025-08-04 17:02:31.468939

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8dec5209111'
down_revision = 'ed182a6fc9c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_availability_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    
    # --- CAMBIO CLAVE AQUÍ ---
    # Le decimos a Alembic que use el tipo ENUM existente y que NO intente crearlo de nuevo.
    sa.Column('dia_semana', postgresql.ENUM('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO', name='dayofweektype_enum', create_type=False), nullable=False),
    
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Esta sección ya está bien, crea los índices después de crear la tabla.
    with op.batch_alter_table('staff_availability_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_availability_rules_dia_semana'), ['dia_semana'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_availability_rules_staff_id'), ['staff_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_availability_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_availability_rules_staff_id'))
        batch_op.drop_index(batch_op.f('ix_staff_availability_rules_dia_semana'))

    op.drop_table('staff_availability_rules')
    
    # --- CAMBIO OPCIONAL PERO RECOMENDADO ---
    # Al hacer downgrade, también eliminamos el tipo ENUM, pero solo si no está en uso
    # por otras tablas (como 'availability_rules'). Para ser seguros, lo dejamos como está,
    # ya que el tipo ENUM es compartido. Si quisiéramos borrarlo, sería:
    # op.execute("DROP TYPE dayofweektype_enum")
    
    # ### end Alembic commands ###