"""add whatsapp_invite table

Revision ID: dfd4eed74b06
Revises: 35ab7f11c179
Create Date: 2025-08-14 16:03:53.731238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd4eed74b06'
down_revision = '35ab7f11c179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('phone_e164', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('whatsapp_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_invites_phone_e164'), ['phone_e164'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_invites_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_invites_token'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_invites_phone_e164'))

    op.drop_table('whatsapp_invites')
    # ### end Alembic commands ###
