"""Add staff management models

Revision ID: ed182a6fc9c8
Revises: 177cd566f81d
Create Date: 2025-08-03 16:57:54.317248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed182a6fc9c8'
down_revision = '177cd566f81d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_services',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('staff_id', 'service_id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_appointments_staff_id'), ['staff_id'], unique=False)
        batch_op.create_foreign_key(None, 'staff', ['staff_id'], ['id'])

    with op.batch_alter_table('establishments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_multiple_staff', sa.Boolean(), nullable=False))

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_staff_user_id'), ['user_id'], unique=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.drop_column('email_contacto')
        batch_op.drop_column('nombre')
        batch_op.drop_column('telefono_contacto')
        batch_op.drop_column('visible_web')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible_web', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('telefono_contacto', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email_contacto', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_staff_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('establishments', schema=None) as batch_op:
        batch_op.drop_column('has_multiple_staff')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_appointments_staff_id'))
        batch_op.drop_column('staff_id')

    op.drop_table('staff_services')
    # ### end Alembic commands ###
